/** Curated suggestions shared by Google Fonts + Bunny Fonts naming. */
globalThis.TypeCascadeFontCatalog = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Source Sans 3",
  "Nunito",
  "Poppins",
  "Raleway",
  "Work Sans",
  "DM Sans",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "IBM Plex Mono",
  "Merriweather",
  "Playfair Display",
  "Fraunces",
  "Libre Baskerville",
  "Lora",
  "Source Serif 4",
  "Crimson Pro",
  "Instrument Serif",
  "Space Grotesk",
  "Space Mono",
  "JetBrains Mono",
  "Fira Code",
  "Inconsolata",
  "Oswald",
  "Bebas Neue",
  "Archivo",
  "Manrope",
  "Outfit",
  "Sora",
  "Figtree",
  "Plus Jakarta Sans",
];
